# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now=True, null=True)),
                ('date_end', models.DateTimeField(auto_now=True, null=True)),
                ('hr', models.SmallIntegerField(default=0, null=True)),
                ('minut', models.SmallIntegerField(default=0, null=True)),
                ('latitude', models.IntegerField(default=0)),
                ('longitude', models.IntegerField(default=0)),
                ('plates', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('FR', 'Libre'), ('OC', 'Ocupado'), ('AL', 'Alerta')], default='FR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_start', models.CharField(default='', max_length=15, null=True)),
                ('street_end', models.CharField(default='', max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='supervisor',
            name='terminal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='parkin.Terminal'),
        ),
    ]
