# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parkin', '0002_auto_20181126_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
