# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkin', '0003_auto_20181127_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parkin'),
        ),
    ]
